services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "3031:3031"
    volumes:
      - /Users/charlie/.colima/default/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
